version: '3'
services:
    web:
        image: wordpress
        restart: always
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST=mysql:3306
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=super_secret_password
        ports:
            - "8082:80"
        volumes:
            - ${PWD}/wp-content/themes/WTCO_NewTheme:/var/www/html/wp-content/themes/WTCO_NewTheme
            - ${PWD}/wp-content/plugins/:/var/www/html/wp-content/plugins
            - ${PWD}/wp-content/:/var/www/html/wp-content    
            - ${PWD}/php.ini:/var/www/html/php.ini
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=super_secret_password
            - MYSQL_DATABASE=wordpress
            - MYSQL_USERNAME=root
        volumes:
            - ./database:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mysql
        ports:
          - 8181:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: super_secret_password
          PMA_ARBITRARY: 1
          PMA_HOST: mysql